### ISSUE TITLE
InvocationTargetException when reading MediaEvent model.yaml 

### ISSUE THREAD

**Issue by isalvadori** [smart-data-models/dataModel.Multimedia#2]
Hi, 
  I am trying to read the MediaEvent model.yaml file but I am getting an `InvocationTargetException`.
I am using `org.snakeyaml:snakeyaml-engine:2.3` to read it.
I can read all the other .yaml models just fine. The only problem is with this one.

**Comment by albertoabellagarcia** [comment]
could it be because it has a recursive attribute? (we have already asked for a new version)

**Comment by isalvadori** [comment]
It might be it then!
Thanks!
